// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technical_tests_backend_ssr.Data;

#nullable disable

namespace technical_tests_backend_ssr.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250529005556_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Email = "juan.perez@email.com",
                            Nombre = "Juan",
                            Telefono = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "González",
                            Email = "maria.gonzalez@email.com",
                            Nombre = "María",
                            Telefono = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rodríguez",
                            Email = "carlos.rodriguez@email.com",
                            Nombre = "Carlos",
                            Telefono = "5555555555"
                        });
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.ServicioPostVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ServiciosPostVenta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Estado = "Completado",
                            Fecha = new DateTime(2025, 5, 8, 21, 55, 55, 815, DateTimeKind.Local).AddTicks(6808),
                            TipoServicio = "Mantenimiento Regular"
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Estado = "En Proceso",
                            Fecha = new DateTime(2025, 5, 18, 21, 55, 55, 815, DateTimeKind.Local).AddTicks(6811),
                            TipoServicio = "Reparación de Frenos"
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 3,
                            Estado = "Pendiente",
                            Fecha = new DateTime(2025, 5, 23, 21, 55, 55, 815, DateTimeKind.Local).AddTicks(6813),
                            TipoServicio = "Cambio de Aceite"
                        });
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Año = 2023,
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            Precio = 25000.00m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 2,
                            Año = 2023,
                            Marca = "Honda",
                            Modelo = "Civic",
                            Precio = 23000.00m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 3,
                            Año = 2023,
                            Marca = "Ford",
                            Modelo = "Mustang",
                            Precio = 45000.00m,
                            Stock = 2
                        });
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Ventas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Fecha = new DateTime(2025, 4, 28, 21, 55, 55, 815, DateTimeKind.Local).AddTicks(6742),
                            Total = 25000.00m,
                            VehiculoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Fecha = new DateTime(2025, 5, 13, 21, 55, 55, 815, DateTimeKind.Local).AddTicks(6776),
                            Total = 23000.00m,
                            VehiculoId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 3,
                            Fecha = new DateTime(2025, 5, 21, 21, 55, 55, 815, DateTimeKind.Local).AddTicks(6779),
                            Total = 45000.00m,
                            VehiculoId = 3
                        });
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.ServicioPostVenta", b =>
                {
                    b.HasOne("technical_tests_backend_ssr.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Venta", b =>
                {
                    b.HasOne("technical_tests_backend_ssr.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("technical_tests_backend_ssr.Models.Vehiculo", null)
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
